export const projects = [
  { id: 0,
    title: 'Travis River Jones Foundation',
    pageLink: "https://www.trjf.org/",
    gitHubLink: 'https://github.com/brandonmcconathy/trjfoundation',
    imgPath: "/projectimgs/trjfoundation.png",
    tech: 'React.js, Next.js, Firebase, JavaScript, Tailwind CSS',
    description: "Users are able to submit applications to dynamically updating scholarships. Admin pages secured by Google OAuth where admins can update scholarships and recipients as well as view applications and email list."},
  { id: 1,
    title: 'Christmas List',
    pageLink: "https://family-christmas-list.vercel.app/",
    gitHubLink: 'https://github.com/brandonmcconathy/christmas-list-react',
    imgPath: "/projectimgs/christmas-list.png",
    tech: 'React.js, Next.js, Firebase, TypeScript, Tailwind CSS',
    description: "Users are able to add items to their list by using their name. Users can also view the lists that every other user has made."}, 
  { id: 2,
    title: 'Gift Card Tracker',
    pageLink: "https://gift-card-tracker.vercel.app/",
    gitHubLink: 'https://github.com/brandonmcconathy/gift-card-tracker',
    imgPath: "/projectimgs/gift-card-tracker.png",
    tech: 'React.js, Next.js, Firebase, TypeScript, Tailwind CSS',
    description: "Users can add gift cards to lists which are differentiated by place and dynamically update. Users can view, update and delete gift cards."},
  { id: 3,
    title: 'Drone Delivery Simulation',
    pageLink: "",
    gitHubLink: 'https://github.com/brandonmcconathy/Drone-Delivery-Simulation',
    imgPath: "/projectimgs/christmas-list.png",
    tech: 'MATLAB',
    description: "Heuristic approach to a truck and drones model for last-mile delivery. We consider the problem of truck and drone delivery scheduling, following work done by Moshref-Javadi et al. Given a depot location and a set of customer locations, the goal is to determine which customers should be served by a truck and which should be served by drones that depart and return to the truck. Moreover, the schedule must specify the customer visitation order for the truck and the departure and rendezvous stops for the drones. We present preliminary results from a heuristic algorithm with the goal of minimizing the total customer waiting time."},
  { id: 4,
    title: 'Running Buddy',
    pageLink: "",
    gitHubLink: 'https://github.com/brandonmcconathy/Running-Buddy',
    imgPath: "/projectimgs/christmas-list.png",
    tech: 'Swift',
    description: "Users can calculate how many miles to run each week. Users can also calculate the pace or finish time of a race."}]