export const projects = [
  { id: 0,
    title: 'Travis River Jones Foundation',
    pageLink: "https://www.trjf.org/",
    gitHubLink: 'https://github.com/brandonmcconathy/trjfoundation',
    imgPath: "/projectimgs/trjfoundation-medium.png",
    tech: 'React.js, Next.js, Firebase, Javascript, Tailwind CSS',
    description: "Users are able to submit applications to dynamically updating scholarships. Admin pages secured by Google OAuth where admins can update scholarships and recipients as well as view applications and email list."},
  { id: 1,
    title: 'Christmas List',
    pageLink: "https://family-christmas-list.vercel.app/",
    gitHubLink: 'https://github.com/brandonmcconathy/christmas-list-react',
    imgPath: "/projectimgs/christmas-list.png",
    tech: 'React.js, Next.js, Firebase, Javascript, Tailwind CSS',
    description: "Users are able to add items to their list by using their name. Users can also view the lists that every other user has inputted."},
  { id: 2,
    title: 'Travis River Jones Foundation',
    pageLink: "https://www.trjf.org/",
    gitHubLink: 'https://github.com/brandonmcconathy/trjfoundation',
    imgPath: "/projectimgs/trjfoundation-medium.png",
    tech: 'React.js, Next.js, Firebase, Javascript, Tailwind CSS',
    description: "Built using React.js, Next.js, Firebase, Javascript, and Tailwind CSS."},
  { id: 3,
    title: 'Travis River Jones Foundation',
    pageLink: "https://www.trjf.org/",
    gitHubLink: 'https://github.com/brandonmcconathy/trjfoundation',
    imgPath: "/projectimgs/trjfoundation-medium.png",
    tech: 'React.js, Next.js, Firebase, Javascript, Tailwind CSS',
    description: "Built using React.js, Next.js, Firebase, Javascript, and Tailwind CSS."},
  { id: 4,
    title: 'Travis River Jones Foundation',
    pageLink: "",
    gitHubLink: 'https://github.com/brandonmcconathy/trjfoundation',
    imgPath: "/projectimgs/trjfoundation-medium.png",
    tech: 'React.js, Next.js, Firebase, Javascript, Tailwind CSS',
    description: "Built using React.js, Next.js, Firebase, Javascript, and Tailwind CSS."}]